name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: sudo apt-get install g++ -y

    - name: Compile code
      run: g++ -o test_program parcial_1.cpp

    - name: Run tests
      run: ./test_program

