name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: 'gcc'

    - name: Build and run tests
      run: |
        sudo apt-get install -y g++
        cd src
        g++ -o parcial_1 parcial_1.cpp
        ./parcial_1

